export * as adminController from "./admin.controller";
export * as coachController from "./coach.controller";
export * as employeeController from "./employee.controller";
export * as hypothesisController from "./hypothesis.controller";
export * as judgeController from "./judge.controller";
export * as projectAdminController from "./project.admin.controller";
export * as projectCoachController from "./project.coach.controller";
export * as projectEmployeeController from "./project.employee.controller";
export * as projectJudgeController from "./project.judge.controller";
